/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-06-09 14:47:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.principal;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.ModelLogin;

public final class usuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1654268678105L));
    _jspx_dependants.put("jar:file:/C:/Users/clown/OneDrive/Documentos/Jdev-Treinamento/Workspace-Jsp1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/curso-jsp/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602884772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.ModelLogin");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Pre-loader start -->\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "theme-loader.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Pre-loader end -->\r\n");
      out.write("	<div id=\"pcoded\" class=\"pcoded\">\r\n");
      out.write("		<div class=\"pcoded-overlay-box\"></div>\r\n");
      out.write("		<div class=\"pcoded-container navbar-wrapper\">\r\n");
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"pcoded-main-container\">\r\n");
      out.write("				<div class=\"pcoded-wrapper\">\r\n");
      out.write("\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbarmainmenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"pcoded-content\">\r\n");
      out.write("						<!-- Page-header start -->\r\n");
      out.write("\r\n");
      out.write("						");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "page-header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- Page-header end -->\r\n");
      out.write("						<div class=\"pcoded-inner-content\">\r\n");
      out.write("							<!-- Main-body start -->\r\n");
      out.write("							<div class=\"main-body\">\r\n");
      out.write("								<div class=\"page-wrapper\">\r\n");
      out.write("									<!-- Page-body start -->\r\n");
      out.write("									<div class=\"page-body\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-sm-12\">\r\n");
      out.write("												<!-- Basic Form Inputs card start -->\r\n");
      out.write("												<div class=\"card\">\r\n");
      out.write("													<div class=\"card-block\">\r\n");
      out.write("														<h4 class=\"sub-title\">Cad. Usuário</h4>\r\n");
      out.write("\r\n");
      out.write("														<form class=\"form-material\" enctype=\"multipart/form-data\"\r\n");
      out.write("															action=\"");
      out.print(request.getContextPath());
      out.write("/ServletUsuarioController\"\r\n");
      out.write("															method=\"post\" id=\"formUser\">\r\n");
      out.write("\r\n");
      out.write("															<input type=\"hidden\" name=\"acao\" id=\"acao\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"id\" id=\"id\"\r\n");
      out.write("																	class=\"form-control\" readonly=\"readonly\"\r\n");
      out.write("																	value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">ID:</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default input-group mb-4\">\r\n");
      out.write("																<div class=\"input-group-prepend\">\r\n");
      out.write("																	");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /principal/usuario.jsp(65,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.fotouser != '' && modolLogin.fotouser != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("																		<a\r\n");
            out.write("																			href=\"");
            out.print( request.getContextPath());
            out.write("/ServletUsuarioController?acao=downloadFoto&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("																			<img alt=\"Imagem User\" id=\"fotoembase64\"\r\n");
            out.write("																			src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.fotouser}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"70px\">\r\n");
            out.write("																		</a>\r\n");
            out.write("																	");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("																	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("																</div>\r\n");
      out.write("																<input type=\"file\" id=\"fileFoto\" name=\"fileFoto\"\r\n");
      out.write("																	accept=\"image/*\"\r\n");
      out.write("																	onchange=\"visualizarImg('fotoembase64', 'fileFoto');\"\r\n");
      out.write("																	class=\"form-control-file\"\r\n");
      out.write("																	style=\"margin-top: 15px; margin-left: 5px;\">\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"nome\" id=\"nome\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.nome}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">Nome:</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">E-mail:</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<select class=\"form-control\"\r\n");
      out.write("																	aria-label=\"Default select example\" name=\"perfil\">\r\n");
      out.write("																	<option disabled=\"disabled\">[Selecione o\r\n");
      out.write("																		Perfil]</option>\r\n");
      out.write("\r\n");
      out.write("																	<option value=\"ADMIN\"\r\n");
      out.write("																		");
ModelLogin modelLogin = (ModelLogin) request.getAttribute("modolLogin");

if (modelLogin != null && modelLogin.getPerfil().toString().equals("FEMININO")) {

	out.print("selected=\"selected\"");

}
      out.write(">Admin</option>\r\n");
      out.write("\r\n");
      out.write("																	<option value=\"SECRETARIA\"\r\n");
      out.write("																		");
modelLogin = (ModelLogin) request.getAttribute("modolLogin");

if (modelLogin != null && modelLogin.getPerfil().toString().equals("SECRETARIA")) {

	out.print("selected=\"selected\"");

}
      out.write(">Secretária</option>\r\n");
      out.write("\r\n");
      out.write("																	<option value=\"AUXILIAR\"\r\n");
      out.write("																		");
modelLogin = (ModelLogin) request.getAttribute("modolLogin");

if (modelLogin != null && modelLogin.getPerfil().toString().equals("AUXILIAR")) {

	out.print("selected=\"selected\"");

}
      out.write(">Auxiliar</option>\r\n");
      out.write("\r\n");
      out.write("																</select> <span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Perfil:</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input onblur=\"pesquisaCep();\" type=\"text\" name=\"cep\"\r\n");
      out.write("																	id=\"cep\" class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.cep}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">CEP</label>\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"logradouro\" id=\"logradouro\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.logradouro}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Logradouro</label>\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"bairro\" id=\"bairro\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.bairro}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Bairro</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"localidade\" id=\"localidade\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.localidade}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Localidade</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"uf\" id=\"uf\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.uf}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">Estado</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"numero\" id=\"numero\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.numero}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Numero</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"text\" name=\"login\" id=\"login\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.login}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Login</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"password\" name=\"senha\" id=\"senha\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"\r\n");
      out.write("																	autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.senha}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("																<span class=\"form-bar\"></span> <label\r\n");
      out.write("																	class=\"float-label\">Senha</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-default form-static-label\">\r\n");
      out.write("																<input type=\"radio\" name=\"sexo\" checked=\"checked\"\r\n");
      out.write("																	value=\"MASCULINO\"\r\n");
      out.write("																	");
modelLogin = (ModelLogin) request.getAttribute("modolLogin");

if (modelLogin != null && modelLogin.getSexo().toString().equals("MASCULINO")) {

	out.print("checked=\"checked\"");

}
      out.write(">Masculino</>\r\n");
      out.write("\r\n");
      out.write("																<input type=\"radio\" name=\"sexo\" value=\"FEMININO\"\r\n");
      out.write("																	");
modelLogin = (ModelLogin) request.getAttribute("modolLogin");

if (modelLogin != null && modelLogin.getSexo().toString().equals("FEMININO")) {

	out.print("checked=\"checked\"");

}
      out.write(">Feminino</>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<button type=\"button\"\r\n");
      out.write("																class=\"btn btn-primary waves-effect waves-light\"\r\n");
      out.write("																onclick=\"limparForm();\">Novo</button>\r\n");
      out.write("															<button class=\"btn btn-success waves-effect waves-light\">Salvar</button>\r\n");
      out.write("															<button type=\"button\"\r\n");
      out.write("																class=\"btn btn-info waves-effect waves-light\"\r\n");
      out.write("																onclick=\"criarDeleteComAjax();\">Excluir</button>\r\n");
      out.write("																\r\n");
      out.write("																");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /principal/usuario.jsp(234,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.id > 0}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("																<a href=\"");
            out.print(request.getContextPath());
            out.write("/ServletTelefone?iduser=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-primary waves-effect waves-light\">Telefone</a>\r\n");
            out.write("																");
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("																\r\n");
      out.write("															<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("																data-toggle=\"modal\" data-target=\"#exampleModalUsuario\">Pesquisar</button>\r\n");
      out.write("														</form>\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<span id=\"msg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("										<div style=\"height: 300px; overflow: scroll;\">\r\n");
      out.write("											<table class=\"table\" id=\"tabelaresultadosview\">\r\n");
      out.write("												<thead>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th scope=\"col\">ID</th>\r\n");
      out.write("														<th scope=\"col\">Nome</th>\r\n");
      out.write("														<th scope=\"col\">Ver</th>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</thead>\r\n");
      out.write("												<tbody>\r\n");
      out.write("													");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /principal/usuario.jsp(257,13) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/principal/usuario.jsp(257,13) '${modelLogins}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${modelLogins}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /principal/usuario.jsp(257,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("ml");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("														<tr>\r\n");
              out.write("															<td>");
              if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("</td>\r\n");
              out.write("															<td>");
              if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("</td>\r\n");
              out.write("															<td><a class=\"btn btn-success\"\r\n");
              out.write("																href=\"");
              out.print( request.getContextPath() );
              out.write("/ServletUsuarioController?acao=buscarEditar&id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">Ver</a></td>\r\n");
              out.write("														</tr>\r\n");
              out.write("													");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("												</tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<nav aria-label=\"Page navigation example\">\r\n");
      out.write("											<ul class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("												");

												int totalPagina = (int) request.getAttribute("totalPagina");

												for (int p = 0; p < totalPagina; p++) {
													String url = request.getContextPath() + "/ServletUsuarioController?acao=paginar&pagina=" + (p * 5);
													out.print("<li class=\"page-item\"><a class=\"page-link\" href=\"" + url + "\">" + (p + 1) + "</a></li>");

												}
												
      out.write("\r\n");
      out.write("											</ul>\r\n");
      out.write("										</nav>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- Page-body end -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"styleSelector\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "javascriptfile.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModalUsuario\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Pesquisa de\r\n");
      out.write("						usuário</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"input-group mb-3\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" placeholder=\"Nome\"\r\n");
      out.write("							aria-label=\"nome\" id=\"nomeBusca\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("						<div class=\"input-group-append\">\r\n");
      out.write("							<button class=\"btn btn-success\" type=\"button\"\r\n");
      out.write("								onclick=\"buscarUsuario();\">Buscar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div style=\"height: 300px; overflow: scroll;\">\r\n");
      out.write("						<table class=\"table\" id=\"tabelaresultados\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">ID</th>\r\n");
      out.write("									<th scope=\"col\">Nome</th>\r\n");
      out.write("									<th scope=\"col\">Ver</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<nav aria-label=\"Page navigation example\">\r\n");
      out.write("						<ul class=\"pagination\" id=\"ulPaginacaoUserAjax\">\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("\r\n");
      out.write("					<span id=\"totalResultados\"></span>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function pesquisaCep() {\r\n");
      out.write("			var cep = $(\"#cep\").val();\r\n");
      out.write("\r\n");
      out.write("			$.getJSON(\"https://viacep.com.br/ws/\"+cep+\"/json/?callback=?\",\r\n");
      out.write("					function(dados) {\r\n");
      out.write("\r\n");
      out.write("						if (!(\"erro\" in dados)) {\r\n");
      out.write("							$(\"#cep\").val(dados.cep);\r\n");
      out.write("							$(\"#logradouro\").val(dados.logradouro);\r\n");
      out.write("							$(\"#bairro\").val(dados.bairro);\r\n");
      out.write("							$(\"#localidade\").val(dados.localidade);\r\n");
      out.write("							$(\"#uf\").val(dados.uf);\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("					});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function visualizarImg(fotoembase64, filefoto) {\r\n");
      out.write("\r\n");
      out.write("			var preview = document.getElementById(fotoembase64); // campo IMG html\r\n");
      out.write("			var fileUser = document.getElementById(filefoto).files[0];\r\n");
      out.write("			var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("			reader.onloadend = function() {\r\n");
      out.write("				preview.src = reader.result; /*Carrega a foto na tela*/\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			if (fileUser) {\r\n");
      out.write("				reader.readAsDataURL(fileUser); /*Preview da imagem*/\r\n");
      out.write("			} else {\r\n");
      out.write("				preview.src = '';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function verEditar(id) {\r\n");
      out.write("\r\n");
      out.write("			var urlAction = document.getElementById('formUser').action;\r\n");
      out.write("\r\n");
      out.write("			window.location.href = urlAction + '?acao=buscarEditar&id=' + id;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function buscaUserPagAjax(url) {\r\n");
      out.write("\r\n");
      out.write("			var urlAction = document.getElementById('formUser').action;\r\n");
      out.write("			var nomeBusca = document.getElementById('nomeBusca').value;\r\n");
      out.write("\r\n");
      out.write("			$\r\n");
      out.write("					.ajax(\r\n");
      out.write("							{\r\n");
      out.write("								method : \"get\",\r\n");
      out.write("								url : urlAction,\r\n");
      out.write("								data : url,\r\n");
      out.write("								success : function(response, textStatus, xhr) {\r\n");
      out.write("\r\n");
      out.write("									var json = JSON.parse(response);\r\n");
      out.write("\r\n");
      out.write("									$('#tabelaresultados > tbody > tr')\r\n");
      out.write("											.remove();\r\n");
      out.write("									$(\"#ulPaginacaoUserAjax > li\").remove();\r\n");
      out.write("\r\n");
      out.write("									for (var p = 0; p < json.length; p++) {\r\n");
      out.write("										$('#tabelaresultados > tbody')\r\n");
      out.write("												.append(\r\n");
      out.write("														'<tr> <td>'\r\n");
      out.write("																+ json[p].id\r\n");
      out.write("																+ '</td> <td> '\r\n");
      out.write("																+ json[p].nome\r\n");
      out.write("																+ '</td> <td><button onclick=\"verEditar('\r\n");
      out.write("																+ json[p].id\r\n");
      out.write("																+ ')\" type=\"button\" class=\"btn btn-info\">Ver</button></td></tr>');\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									document.getElementById('totalResultados').textContent = 'Resultados: '\r\n");
      out.write("											+ json.length;\r\n");
      out.write("\r\n");
      out.write("									var totalPagina = xhr\r\n");
      out.write("											.getResponseHeader(\"totalPagina\");\r\n");
      out.write("\r\n");
      out.write("									for (var p = 0; p < totalPagina; p++) {\r\n");
      out.write("\r\n");
      out.write("										var url = 'nomeBusca='\r\n");
      out.write("												+ nomeBusca\r\n");
      out.write("												+ '&acao=buscarUserAjaxPage&pagina='\r\n");
      out.write("												+ (p * 5);\r\n");
      out.write("\r\n");
      out.write("										$(\"#ulPaginacaoUserAjax\")\r\n");
      out.write("												.append(\r\n");
      out.write("														'<li class=\"page-item\"><a class=\"page-link\" href=\"#\" onclick=\"buscaUserPagAjax(\\''\r\n");
      out.write("																+ url\r\n");
      out.write("																+ '\\')\">'\r\n");
      out.write("																+ (p + 1)\r\n");
      out.write("																+ '</a></li>');\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("								}\r\n");
      out.write("\r\n");
      out.write("							}).fail(\r\n");
      out.write("							function(xhr, status, errorThrown) {\r\n");
      out.write("								alert('Erro ao buscar usuário por nome: '\r\n");
      out.write("										+ xhr.responseText);\r\n");
      out.write("							});\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function buscarUsuario() {\r\n");
      out.write("\r\n");
      out.write("			var nomeBusca = document.getElementById('nomeBusca').value;\r\n");
      out.write("\r\n");
      out.write("			if (nomeBusca != null && nomeBusca != '' && nomeBusca.trim() != '') { /*Validando que tem que ter valor pra buscar no banco*/\r\n");
      out.write("\r\n");
      out.write("				var urlAction = document.getElementById('formUser').action;\r\n");
      out.write("\r\n");
      out.write("				$\r\n");
      out.write("						.ajax(\r\n");
      out.write("								{\r\n");
      out.write("\r\n");
      out.write("									method : \"get\",\r\n");
      out.write("									url : urlAction,\r\n");
      out.write("									data : \"nomeBusca=\" + nomeBusca\r\n");
      out.write("											+ '&acao=buscarUserAjax',\r\n");
      out.write("									success : function(response, textStatus,\r\n");
      out.write("											xhr) {\r\n");
      out.write("\r\n");
      out.write("										var json = JSON.parse(response);\r\n");
      out.write("\r\n");
      out.write("										$('#tabelaresultados > tbody > tr')\r\n");
      out.write("												.remove();\r\n");
      out.write("										$(\"#ulPaginacaoUserAjax > li\").remove();\r\n");
      out.write("\r\n");
      out.write("										for (var p = 0; p < json.length; p++) {\r\n");
      out.write("											$('#tabelaresultados > tbody')\r\n");
      out.write("													.append(\r\n");
      out.write("															'<tr> <td>'\r\n");
      out.write("																	+ json[p].id\r\n");
      out.write("																	+ '</td> <td> '\r\n");
      out.write("																	+ json[p].nome\r\n");
      out.write("																	+ '</td> <td><button onclick=\"verEditar('\r\n");
      out.write("																	+ json[p].id\r\n");
      out.write("																	+ ')\" type=\"button\" class=\"btn btn-info\">Ver</button></td></tr>');\r\n");
      out.write("										}\r\n");
      out.write("\r\n");
      out.write("										document\r\n");
      out.write("												.getElementById('totalResultados').textContent = 'Resultados: '\r\n");
      out.write("												+ json.length;\r\n");
      out.write("\r\n");
      out.write("										var totalPagina = xhr\r\n");
      out.write("												.getResponseHeader(\"totalPagina\");\r\n");
      out.write("\r\n");
      out.write("										for (var p = 0; p < totalPagina; p++) {\r\n");
      out.write("\r\n");
      out.write("											var url = 'nomeBusca='\r\n");
      out.write("													+ nomeBusca\r\n");
      out.write("													+ '&acao=buscarUserAjaxPage&pagina='\r\n");
      out.write("													+ (p * 5);\r\n");
      out.write("\r\n");
      out.write("											$(\"#ulPaginacaoUserAjax\")\r\n");
      out.write("													.append(\r\n");
      out.write("															'<li class=\"page-item\"><a class=\"page-link\" href=\"#\" onclick=\"buscaUserPagAjax(\\''\r\n");
      out.write("																	+ url\r\n");
      out.write("																	+ '\\')\">'\r\n");
      out.write("																	+ (p + 1)\r\n");
      out.write("																	+ '</a></li>');\r\n");
      out.write("\r\n");
      out.write("										}\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("								}).fail(\r\n");
      out.write("								function(xhr, status, errorThrown) {\r\n");
      out.write("									alert('Erro ao buscar usuário por nome: '\r\n");
      out.write("											+ xhr.responseText);\r\n");
      out.write("								});\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function criarDeleteComAjax() {\r\n");
      out.write("\r\n");
      out.write("			if (confirm('Deseja realmente excluir os dados?')) {\r\n");
      out.write("\r\n");
      out.write("				var urlAction = document.getElementById('formUser').action;\r\n");
      out.write("				var idUser = document.getElementById('id').value;\r\n");
      out.write("\r\n");
      out.write("				$.ajax({\r\n");
      out.write("\r\n");
      out.write("					method : \"get\",\r\n");
      out.write("					url : urlAction,\r\n");
      out.write("					data : \"id=\" + idUser + '&acao=deletarajax',\r\n");
      out.write("					success : function(response) {\r\n");
      out.write("\r\n");
      out.write("						limparForm();\r\n");
      out.write("						document.getElementById('msg').textContent = response;\r\n");
      out.write("					}\r\n");
      out.write("\r\n");
      out.write("				}).fail(\r\n");
      out.write("						function(xhr, status, errorThrown) {\r\n");
      out.write("							alert('Erro ao deletar usuário por id: '\r\n");
      out.write("									+ xhr.responseText);\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function criarDelete() {\r\n");
      out.write("\r\n");
      out.write("			if (confirm('Deseja realmente excluir os dados?')) {\r\n");
      out.write("\r\n");
      out.write("				document.getElementById(\"formUser\").method = 'get';\r\n");
      out.write("				document.getElementById(\"acao\").value = 'deletar';\r\n");
      out.write("				document.getElementById(\"formUser\").submit();\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function limparForm() {\r\n");
      out.write("\r\n");
      out.write("			var elementos = document.getElementById(\"formUser\").elements; /*Retorna os elementos html dentro do form*/\r\n");
      out.write("\r\n");
      out.write("			for (p = 0; p < elementos.length; p++) {\r\n");
      out.write("				elementos[p].value = '';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /principal/usuario.jsp(74,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modolLogin.fotouser == '' || modolLogin.fotouser == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("																		<img alt=\"Imagem User\" id=\"fotoembase64\"\r\n");
          out.write("																			src=\"assets/images/userImg.png\" width=\"70px\">\r\n");
          out.write("																	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /principal/usuario.jsp(259,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.id}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /principal/usuario.jsp(260,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.nome}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
